// ================================================================================================
//  workshop
//  Copyright (C) 2021 Tim Leonard
// ================================================================================================
#pragma once

#include "workshop.render_interface/ri_interface.h"
#include "workshop.render_interface.vulkan/vulkan_headers.h"
#include "workshop.render_interface/ri_types.h"

#include <array>
#include <unordered_set>
#include <mutex>

namespace ws {

class vulkan_ri_command_queue;
class vulkan_ri_upload_manager;
class vulkan_ri_tile_manager;
class vulkan_ri_query_manager;
class vulkan_ri_descriptor_table;
class vulkan_ri_small_buffer_allocator;
class vulkan_ri_raytracing_tlas;
class vulkan_ri_raytracing_blas;
class vulkan_ri_param_block;

// ================================================================================================
//  Implementation of a renderer using Vulkan.
// ================================================================================================
class vulkan_render_interface : public ri_interface
{
public:
    // How many frames can be in the pipeline at a given time, including
    // the one currently being built.
    // The number of swap chain targets is one lower than this.
    constexpr static size_t k_max_pipeline_depth = 3;

    // Number of "real" bindless descriptor table types that have a vulkan descriptor
    // equivalent (ie. excluding render_target/depth_stencil, which dynamic rendering handles
    // via raw image views instead). These occupy pipeline layout set indices 1-9, matching
    // the HLSL register(x, spaceN) layout emitted by shader_loader.cpp's autogenerated stub.
    constexpr static size_t k_bindless_set_count = 9;

    // Maximum amount of descriptors in each table.
    constexpr static std::array<size_t, static_cast<int>(ri_descriptor_table::COUNT)> k_descriptor_table_sizes = {
        100,    // texture_1d
        100000, // texture_2d
        1000,   // texture_3d
        100,    // texture_cube
        100,    // sampler
        300000, // buffer
        300000, // rwbuffer
        1000,   // rwtexture_2d
        100000, // tlas
        1000,   // render_target (unused, dynamic rendering takes views directly)
        1000,   // depth_stencil (unused, dynamic rendering takes views directly)
    };

    // Maximum amount of queries that can be allocated.
    constexpr static size_t k_maximum_queries = 200;

    // See dx12_render_interface for the meaning of these two parameters, they only affect
    // raytracing shader-binding-table layout.
    vulkan_render_interface(size_t ray_type_count, size_t ray_domain_count);
    virtual ~vulkan_render_interface();

    virtual void register_init(init_list& list) override;
    virtual void begin_frame() override;
    virtual void end_frame() override;
    virtual void flush_uploads() override;
    virtual std::unique_ptr<ri_swapchain> create_swapchain(window& for_window, const char* debug_name = nullptr) override;
    virtual std::unique_ptr<ri_fence> create_fence(const char* debug_name = nullptr) override;
    virtual std::unique_ptr<ri_shader_compiler> create_shader_compiler() override;
    virtual std::unique_ptr<ri_texture_compiler> create_texture_compiler() override;
    virtual std::unique_ptr<ri_pipeline> create_pipeline(const ri_pipeline::create_params& params, const char* debug_name = nullptr) override;
    virtual std::unique_ptr<ri_param_block_archetype> create_param_block_archetype(const ri_param_block_archetype::create_params& params, const char* debug_name = nullptr) override;
    virtual std::unique_ptr<ri_texture> create_texture(const ri_texture::create_params& params, const char* debug_name = nullptr) override;
    virtual std::unique_ptr<ri_sampler> create_sampler(const ri_sampler::create_params& params, const char* debug_name = nullptr) override;
    virtual std::unique_ptr<ri_buffer> create_buffer(const ri_buffer::create_params& params, const char* debug_name = nullptr) override;
    virtual std::unique_ptr<ri_layout_factory> create_layout_factory(ri_data_layout layout, ri_layout_usage usage) override;
    virtual std::unique_ptr<ri_query> create_query(const ri_query::create_params& params, const char* debug_name = nullptr) override;
    virtual std::unique_ptr<ri_raytracing_blas> create_raytracing_blas(const char* debug_name = nullptr) override;
    virtual std::unique_ptr<ri_raytracing_tlas> create_raytracing_tlas(const char* debug_name = nullptr) override;
    virtual std::unique_ptr<ri_staging_buffer> create_staging_buffer(const ri_staging_buffer::create_params& params, std::span<uint8_t> linear_data) override;
    virtual ri_command_queue& get_graphics_queue() override;
    virtual ri_command_queue& get_copy_queue() override;
    virtual size_t get_pipeline_depth() override;
    virtual void defer_delete(deferred_delete_function_t&& func) override;
    virtual void get_vram_usage(size_t& out_local, size_t& out_non_local) override;
    virtual void get_vram_total(size_t& out_local_total, size_t& out_non_local_total) override;
    virtual size_t get_cube_map_face_index(ri_cube_map_face face) override;
    virtual bool check_feature(ri_feature feature) override;

    // Whether VK_KHR_swapchain_mutable_format is available - lets the swapchain create its
    // images in whatever storage format the surface actually supports while still exposing
    // VK_FORMAT_R8G8B8A8_SRGB views, matching the engine's shared render target format config.
    bool is_swapchain_mutable_format_supported() const;

    // Marks a param block as dirty and tells the param block to upload its state
    // the next time uploads are flushed.
    void queue_dirty_param_block(vulkan_ri_param_block* block);
    void dequeue_dirty_param_block(vulkan_ri_param_block* block);
    std::recursive_mutex& get_dirty_param_block_mutex();

    // Drains all of the defered deletes without regard for which frame they should
    // be destroyed on. Be -very- careful with this, the only real usecase is when we are
    // draining the entire pipeline at once.
    void drain_deferred();

    vulkan_ri_upload_manager& get_upload_manager();
    vulkan_ri_tile_manager& get_tile_manager();
    vulkan_ri_query_manager& get_query_manager();

    vulkan_ri_small_buffer_allocator& get_small_buffer_allocator();

    vulkan_ri_descriptor_table& get_descriptor_table(ri_descriptor_table table);

    // Empty set-0 layout shared by every pipeline layout (see vulkan_ri_pipeline.h class
    // comment) - a single persistent instance owned by the renderer, rather than one created
    // and destroyed per-pipeline, since a VkPipelineLayout's constituent set layouts must stay
    // alive for as long as anything created from it is still used (eg. vkCmdBindPipeline),
    // not just through the vkCreate*Pipelines call that references them.
    VkDescriptorSetLayout get_dummy_set_layout();

    size_t get_frame_index();

    size_t get_ray_domain_count();
    size_t get_ray_type_count();

    // Used to queue a rebuild of a tlas/blas resources.
    void queue_as_build(vulkan_ri_raytracing_tlas* tlas);
    void queue_as_build(vulkan_ri_raytracing_blas* blas);

    void dequeue_as_build(vulkan_ri_raytracing_tlas* tlas);
    void dequeue_as_build(vulkan_ri_raytracing_blas* blas);

    // Checks the result of a vulkan call and returns true if it was successful. On failure a
    // debug log is written and the function returns false.
    bool check_result(VkResult result, const char* context);

    // Same as check_result but terminates the program on failure.
    void assert_result(VkResult result, const char* context);

    VkInstance get_instance();
    VkPhysicalDevice get_physical_device();
    VkDevice get_device();

    const VkPhysicalDeviceProperties& get_physical_device_properties();
    const VkPhysicalDeviceMemoryProperties& get_physical_device_memory_properties();
    const VkPhysicalDeviceRayTracingPipelinePropertiesKHR& get_raytracing_pipeline_properties();

    // Finds a memory type index satisfying the given type filter and property flags. Returns
    // false if no suitable memory type is available on this device.
    result<uint32_t> find_memory_type(uint32_t type_filter, VkMemoryPropertyFlags properties);

    // Tags a vulkan object with a debug name (if VK_EXT_debug_utils is available) so validation
    // layer messages naming the object's handle can be traced back to what created it.
    void set_debug_object_name(VkObjectType type, uint64_t handle, const char* name);

    // Manually resolved function pointers for extensions that will never be promoted to
    // vulkan core (VK_KHR_acceleration_structure, VK_KHR_ray_tracing_pipeline,
    // VK_KHR_deferred_host_operations) - these always need vkGetDeviceProcAddr regardless
    // of the core api version targeted, since we deliberately avoid depending on volk.
    PFN_vkGetAccelerationStructureBuildSizesKHR vkGetAccelerationStructureBuildSizesKHR_fn = nullptr;
    PFN_vkCreateAccelerationStructureKHR vkCreateAccelerationStructureKHR_fn = nullptr;
    PFN_vkDestroyAccelerationStructureKHR vkDestroyAccelerationStructureKHR_fn = nullptr;
    PFN_vkCmdBuildAccelerationStructuresKHR vkCmdBuildAccelerationStructuresKHR_fn = nullptr;
    PFN_vkCmdCopyAccelerationStructureKHR vkCmdCopyAccelerationStructureKHR_fn = nullptr;
    PFN_vkCmdWriteAccelerationStructuresPropertiesKHR vkCmdWriteAccelerationStructuresPropertiesKHR_fn = nullptr;
    PFN_vkGetAccelerationStructureDeviceAddressKHR vkGetAccelerationStructureDeviceAddressKHR_fn = nullptr;
    PFN_vkCreateRayTracingPipelinesKHR vkCreateRayTracingPipelinesKHR_fn = nullptr;
    PFN_vkGetRayTracingShaderGroupHandlesKHR vkGetRayTracingShaderGroupHandlesKHR_fn = nullptr;
    PFN_vkCmdTraceRaysKHR vkCmdTraceRaysKHR_fn = nullptr;

    PFN_vkSetDebugUtilsObjectNameEXT vkSetDebugUtilsObjectNameEXT_fn = nullptr;

private:

    result<void> create_device();
    result<void> destroy_device();

    result<void> create_command_queues();
    result<void> destroy_command_queues();

    result<void> create_heaps();
    result<void> destroy_heaps();

    result<void> create_misc();
    result<void> destroy_misc();

    result<void> select_physical_device();
    result<void> select_queue_families();
    result<void> check_feature_support();
    void resolve_extension_functions();

    void process_pending_deletes();

    // Builds pending BLAS's, compacts BLAS's ready for compaction, and builds pending TLAS's,
    // all within a single command list/submission. This must stay a single submission - the
    // acceleration-structure memory barriers recorded within each step only order work within
    // the same command buffer/submission, not across separate vkQueueSubmit calls, and a TLAS
    // build reads BLAS device addresses/data that must be visible by the time it runs.
    void process_as_build_requests();

private:

    VkInstance m_instance = VK_NULL_HANDLE;
    VkDebugUtilsMessengerEXT m_debug_messenger = VK_NULL_HANDLE;

    VkPhysicalDevice m_physical_device = VK_NULL_HANDLE;
    VkDevice m_device = VK_NULL_HANDLE;

    VkPhysicalDeviceProperties m_physical_device_properties = {};
    VkPhysicalDeviceMemoryProperties m_physical_device_memory_properties = {};
    VkPhysicalDeviceRayTracingPipelinePropertiesKHR m_raytracing_pipeline_properties = {};

    uint32_t m_graphics_queue_family = 0;
    uint32_t m_copy_queue_family = 0;

    // Note: deliberately no default member initializer on these - unique_ptr's own default
    // constructor already leaves them null, and (unlike a "= nullptr" initializer) that does
    // not require the pointee's complete type in every translation unit that includes this
    // header, only in the .cpp where vulkan_render_interface's constructor is defined.
    std::unique_ptr<vulkan_ri_command_queue> m_graphics_queue;
    std::unique_ptr<vulkan_ri_command_queue> m_copy_queue;
    std::unique_ptr<vulkan_ri_upload_manager> m_upload_manager;
    std::unique_ptr<vulkan_ri_tile_manager> m_tile_manager;
    std::unique_ptr<vulkan_ri_query_manager> m_query_manager;
    std::unique_ptr<vulkan_ri_small_buffer_allocator> m_small_buffer_allocator;

    std::array<std::unique_ptr<vulkan_ri_descriptor_table>, static_cast<int>(ri_descriptor_table::COUNT)> m_descriptor_tables;

    VkDescriptorSetLayout m_dummy_set_layout = VK_NULL_HANDLE;

    bool m_swapchain_mutable_format_supported = false;

    size_t m_frame_index = 0;

    std::mutex m_pending_deletion_mutex;
    std::array<std::vector<deferred_delete_function_t>, k_max_pipeline_depth> m_pending_deletions;

    std::recursive_mutex m_pending_as_build_mutex;
    std::unordered_set<vulkan_ri_raytracing_blas*> m_pending_blas_builds;
    std::unordered_set<vulkan_ri_raytracing_tlas*> m_pending_tlas_builds;
    std::unordered_set<vulkan_ri_raytracing_blas*> m_pending_blas_compacts;

    std::array<bool, (int)ri_feature::COUNT> m_feature_support = {};

    std::recursive_mutex m_dirty_param_block_mutex;
    std::unordered_set<vulkan_ri_param_block*> m_dirty_param_blocks;
    bool m_flush_upload_reentry = false;

    size_t m_ray_type_count;
    size_t m_ray_domain_count;

    size_t m_vram_total_local = 0;
    size_t m_vram_total_non_local = 0;

};

}; // namespace ws
